site_name: "FFRD | Proposed Standards and Specifications"
site_url: https://fema-ffrd.github.io/specs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.expand

plugins:
  - search
  - include-markdown
  - macros

repo_url: https://github.com/fema-ffrd/specs

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Overview:
    - index.md
    - scope.md
    - terms.md

  - Standards:
    - standards/base_image.md
    - standards/hms_sim.md
    - standards/ras_sim.md

  - Specifications:
    - specifications/base_image.md
    - specifications/hms_sim.md
    - specifications/ras_sim.md

  - Schemas:
    - schemas/base_image.md
    - schemas/hms_sim.md
    - schemas/ras_sim.md


  - Reference Implementations:
    - reference/base_image.md
    - reference/hms_sim.md
    - reference/ras_sim.md

  - Proposals:
    - proposals/conformance/conformance.md

  - Appendix:
    - references.md

