site_name: FEMA FFRD Specifications
site_url: https://fema-ffrd.github.io/specs
theme:
  name: material
  custom_dir: overrides
repo_url: https://github.com/fema-ffrd/specs
extra:
  version:
    provider: mike
markdown_extensions:
  - pymdownx.superfences:  # mermaid diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - "Overview": "index.md"
  - "scope.md"
  - "terms.md"
  - "3. Processes":
    - "processes/hechms.md"
    - "processes/hecras.md"
  - "A. Appendix": 
    - "references.md"
  
