site_name: FEMA FFRD Specifications
site_url: https://fema-ffrd.github.io/specs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.expand

plugins:
  - search
  - include-markdown
  - macros

repo_url: https://github.com/fema-ffrd/specs

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Overview:
    - index.md
    - scope.md
    - terms.md
  - Containers:
    - containers/base.md
    - containers/plugin.md
    - containers/examples.md
  - Schemas:
    - schemas/base_container.md
  - Processes:
    - processes/hechms.md
    - processes/hecras.md
  - Appendix: 
    - references.md
