[project]
name = "fema-ffrd-specs"
version = "0.0.1"
description = "FEMA FFRD Specifications"
dependencies = [
  "mkdocs-material",
  "mike",
  "mkdocs-macros-plugin",
  "mkdocs-include-markdown-plugin",
  "mdformat",
  "pre-commit"
]

[tool.setuptools.packages.find]
exclude = ["*"]
