name: Test Build - HMS Runner

on:
  pull_request:
    branches:
      - main
    paths:
      - 'reference/hms/hms-golang/**'

jobs:
  test-build-hms-runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hms_version: [ "4.10", "4.11", "4.12" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build HMS runner image
        uses: docker/build-push-action@v4
        with:
          context: ./reference/hms/hms-golang
          file: ./reference/hms/hms-golang/Dockerfile
          push: false
          tags: hms-runner:${{ matrix.hms_version }}
          build-args: |
            HMS_VERSION=${{ matrix.hms_version}}
