name: Build and push HMS runner images

on:
  push:
    branches:
      - main
    paths:
      - 'reference/hms/hms-golang/**'

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/hms-runner
  LATEST_HMS_VERSION: "4.13-beta.6"   # for tagging 'latest'

jobs:
  build-push-hms-runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hms_version: [ "4.10", "4.11", "4.12", "4.13-beta.6" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push HMS runner image
        uses: docker/build-push-action@v4
        with:
          context: ./reference/hms/hms-golang
          file: ./reference/hms/hms-golang/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ matrix.hms_version }}
          build-args: |
            HMS_VERSION=${{ matrix.hms_version }}

      - name: Tag latest
        if: ${{ matrix.hms_version == env.LATEST_HMS_VERSION }}
        run: |
          docker pull $IMAGE:${{ matrix.hms_version }}
          docker tag $IMAGE:${{ matrix.hms_version }} $IMAGE:latest
          docker push $IMAGE:latest
