name: Deploy to GitHub Pages; build and push images

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install .

      - name: Markdown formatting check
        run: |
          mdformat --check .

      - name: Build and deploy
        run: |
          pip install ghp-import
          mkdocs build
          ghp-import -n -p -f site
