name: Deploy to GitHub Pages; build and push images

on:
  push:
    branches:
      - main

jobs:
  deploy-specs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install .

      - name: Markdown formatting check
        run: |
          mdformat --check .

      - name: Build and deploy
        run: |
          pip install ghp-import
          mkdocs build
          ghp-import -n -p -f site

  build-push-hms-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push HMS Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./reference/hms/hms-golang
          file: ./reference/hms/hms-golang/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hms-runner:latest
            ghcr.io/${{ github.repository_owner }}/hms-runner:${{ github.sha }}
