name: Test build FFRD images

on:
  pull_request:
    paths:
      - 'reference/base/**'
      - 'reference/hms/hms-golang/**'
      - 'reference/ras/v660/**'
      - '.github/workflows/build-and-push.yml'
      - '.github/workflows/test-build.yml'

env:
  BASE_IMAGE: ffrd-base
  HMS_IMAGE: hms-runner
  RAS_IMAGE: ras-runner
  LATEST_HMS_VERSION: "4.13-beta.6"

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: base
            hms_version: ""
          - image: hms
            hms_version: "4.10"
          - image: hms
            hms_version: "4.11"
          - image: hms
            hms_version: "4.12"
          - image: hms
            hms_version: "4.13-beta.6"
          - image: ras
            hms_version: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build FFRD base image
        uses: docker/build-push-action@v4
        with:
          context: ./reference/base
          file: ./reference/base/Dockerfile
          push: false
          tags: ffrd_base:latest
          load: true

      - name: Build HMS runner image
        if: matrix.image == 'hms'
        uses: docker/build-push-action@v4
        with:
          context: ./reference/hms/hms-golang
          file: ./reference/hms/hms-golang/Dockerfile
          push: false
          tags: ${{ env.HMS_IMAGE }}:${{ matrix.hms_version }}
          build-args: |
            HMS_VERSION=${{ matrix.hms_version }}

      - name: Build RAS v660 image
        if: matrix.image == 'ras'
        uses: docker/build-push-action@v4
        with:
          context: ./reference/ras/v660
          file: ./reference/ras/v660/Dockerfile
          push: false
          tags: ${{ env.RAS_IMAGE }}:test
